[17/May/2018 16:27:12] "GET /naver_crawler_search/index.html HTTP/1.1" 200 6660
[17/May/2018 16:27:12] "GET /static/images/fav-icon.png HTTP/1.1" 200 692
[17/May/2018 16:50:31] "GET /naver_crawler_search/index.html HTTP/1.1" 200 6660
[17/May/2018 16:50:32] "GET /static/images/fav-icon.png HTTP/1.1" 200 692
[17/May/2018 16:59:46] "GET /naver_crawler_search/index.html HTTP/1.1" 200 6807
[17/May/2018 16:59:47] "GET /static/images/fav-icon.png HTTP/1.1" 200 692
Performing system checks...

System check identified no issues (0 silenced).
May 17, 2018 - 16:27:07
Django version 2.0.5, using settings 'myWeb.settings'
Starting development server at http://0.0.0.0:2001/
Quit the server with CONTROL-C.
list index out of range
list index out of range
list index out of range
[17/May/2018 17:12:35] "GET /naver_crawler_search/index.html HTTP/1.1" 200 6834
[17/May/2018 17:12:35] "GET /static/images/fav-icon.png HTTP/1.1" 200 692
[17/May/2018 17:12:37] "GET /naver_crawler_search/index.html HTTP/1.1" 200 6834
[17/May/2018 17:12:37] "GET /static/images/fav-icon.png HTTP/1.1" 200 692
Internal Server Error: /naver_crawler_search/index.html
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.4/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.4/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home2/inseop/DjangoProject/myWeb/hackday_crawler_search/myHome/views.py", line 13, in index
    return render(request,'myHome/index.html',context)
  File "/usr/lib/python3.4/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.4/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.4/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home2/inseop/DjangoProject/myWeb/hackday_crawler_search/myHome/templatetags/search_content.py", line 88, in year
    year = int(year)
ValueError: invalid literal for int() with base 10: 'all&sort=accuracy'
[17/May/2018 17:12:47] "GET /naver_crawler_search/index.html?searchInput=%EB%84%A4%EC%9D%B4%EB%B2%84+%ED%95%B5%EB%8D%B0%EC%9D%B4&year=all&sort=accuracy HTTP/1.1" 500 152581
Performing system checks...

System check identified no issues (0 silenced).
May 17, 2018 - 17:05:42
Django version 2.0.5, using settings 'myWeb.settings'
Starting development server at http://0.0.0.0:2001/
Quit the server with CONTROL-C.
list index out of range
list index out of range
list index out of range
list index out of range
Internal Server Error: /naver_crawler_search/index.html
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.4/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.4/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home2/inseop/DjangoProject/myWeb/hackday_crawler_search/myHome/views.py", line 13, in index
    return render(request,'myHome/index.html',context)
  File "/usr/lib/python3.4/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.4/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.4/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home2/inseop/DjangoProject/myWeb/hackday_crawler_search/myHome/templatetags/search_content.py", line 89, in year
    year = int(year)
ValueError: invalid literal for int() with base 10: 'all'
[17/May/2018 17:15:05] "GET /naver_crawler_search/index.html?searchInput=%EB%84%A4%EC%9D%B4%EB%B2%84+%ED%95%B5%EB%8D%B0%EC%9D%B4&year=all&sort=accuracy HTTP/1.1" 500 152487
Internal Server Error: /naver_crawler_search/index.html
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.4/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.4/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home2/inseop/DjangoProject/myWeb/hackday_crawler_search/myHome/views.py", line 13, in index
    return render(request,'myHome/index.html',context)
  File "/usr/lib/python3.4/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.4/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.4/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home2/inseop/DjangoProject/myWeb/hackday_crawler_search/myHome/templatetags/search_content.py", line 89, in year
    year = int(year)
ValueError: invalid literal for int() with base 10: 'all'
[17/May/2018 17:15:20] "GET /naver_crawler_search/index.html?searchInput=%EB%84%A4%EC%9D%B4%EB%B2%84+%ED%95%B5%EB%8D%B0%EC%9D%B4&year=all&sort=accuracy HTTP/1.1" 500 152486
Performing system checks...

System check identified no issues (0 silenced).
May 17, 2018 - 17:15:00
Django version 2.0.5, using settings 'myWeb.settings'
Starting development server at http://0.0.0.0:2001/
Quit the server with CONTROL-C.
Internal Server Error: /naver_crawler_search/index.html
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.4/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.4/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home2/inseop/DjangoProject/myWeb/hackday_crawler_search/myHome/views.py", line 13, in index
    return render(request,'myHome/index.html',context)
  File "/usr/lib/python3.4/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.4/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.4/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/defaulttags.py", line 314, in render
    return nodelist.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home2/inseop/DjangoProject/myWeb/hackday_crawler_search/myHome/templatetags/search_content.py", line 32, in queryset_search
    year = year.split("20")[1]
IndexError: list index out of range
[17/May/2018 17:16:33] "GET /naver_crawler_search/index.html?searchInput=%EB%84%A4%EC%9D%B4%EB%B2%84+%ED%95%B5%EB%8D%B0%EC%9D%B4&year=all&sort=accuracy HTTP/1.1" 500 193454
Internal Server Error: /naver_crawler_search/index.html
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.4/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.4/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home2/inseop/DjangoProject/myWeb/hackday_crawler_search/myHome/views.py", line 13, in index
    return render(request,'myHome/index.html',context)
  File "/usr/lib/python3.4/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3.4/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.4/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/defaulttags.py", line 314, in render
    return nodelist.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3.4/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.4/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home2/inseop/DjangoProject/myWeb/hackday_crawler_search/myHome/templatetags/search_content.py", line 32, in queryset_search
    year = year.split("20")[1]
IndexError: list index out of range
[17/May/2018 17:22:01] "GET /naver_crawler_search/index.html?searchInput=%EB%84%A4%EC%9D%B4%EB%B2%84+%ED%95%B5%EB%8D%B0%EC%9D%B4&year=all&sort=accuracy HTTP/1.1" 500 193589
Performing system checks...

System check identified no issues (0 silenced).
May 17, 2018 - 17:16:29
Django version 2.0.5, using settings 'myWeb.settings'
Starting development server at http://0.0.0.0:2001/
Quit the server with CONTROL-C.
['네이버', '핵데이']
all&sort=accuracy
['네이버', '핵데이']
all&sort=accuracy
Not Found: /
[17/May/2018 17:23:15] "GET / HTTP/1.1" 404 2464
Not Found: /favicon.ico
[17/May/2018 17:23:15] "GET /favicon.ico HTTP/1.1" 404 2515
Not Found: /favicon.ico
[17/May/2018 17:23:15] "GET /favicon.ico HTTP/1.1" 404 2515
